apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-api
  namespace: trend-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trend-api
  template:
    metadata:
      labels:
        app: trend-api
    spec:
      serviceAccountName: trend-sa
      containers:
        - name: api
          image: REGION-docker.pkg.dev/PROJECT_ID/ImageREPO_NAME/api:latest
          ports:
            - containerPort: 8080
