apiVersion: batch/v1
kind: Job
metadata:
  name: trend-worker
  namespace: trend-platform
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: trend-sa
      containers:
        - name: worker
          image: REGION-docker.pkg.dev/PROJECT_ID/ImageREPO_NAME/worker:latest
